# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Work\CMake\bin\cmake.exe

# The command to remove a file.
RM = D:\Work\CMake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Study\cura-build-3.4.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Study\cura-build-3.4.1\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	D:\Work\CMake\bin\cpack.exe --config ./CPackSourceConfig.cmake E:/Study/cura-build-3.4.1/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	D:\Work\CMake\bin\cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\Work\CMake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\Work\CMake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"_cura\" \"arduino\" \"vcredist\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	D:\Work\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	D:\Work\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	D:\Work\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	D:\Work\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	D:\Work\CMake\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	D:\Work\CMake\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Study\cura-build-3.4.1\build\CMakeFiles E:\Study\cura-build-3.4.1\build\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Study\cura-build-3.4.1\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projects

# Build rule for target.
projects: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 projects
.PHONY : projects

# fast build rule for target.
projects/fast:
	$(MAKE) -f CMakeFiles\projects.dir\build.make CMakeFiles/projects.dir/build
.PHONY : projects/fast

#=============================================================================
# Target rules for targets named build_bundle

# Build rule for target.
build_bundle: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 build_bundle
.PHONY : build_bundle

# fast build rule for target.
build_bundle/fast:
	$(MAKE) -f CMakeFiles\build_bundle.dir\build.make CMakeFiles/build_bundle.dir/build
.PHONY : build_bundle/fast

#=============================================================================
# Target rules for targets named packaging

# Build rule for target.
packaging: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 packaging
.PHONY : packaging

# fast build rule for target.
packaging/fast:
	$(MAKE) -f CMakeFiles\packaging.dir\build.make CMakeFiles/packaging.dir/build
.PHONY : packaging/fast

#=============================================================================
# Target rules for targets named Cura

# Build rule for target.
Cura: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Cura
.PHONY : Cura

# fast build rule for target.
Cura/fast:
	$(MAKE) -f CMakeFiles\Cura.dir\build.make CMakeFiles/Cura.dir/build
.PHONY : Cura/fast

#=============================================================================
# Target rules for targets named Uranium

# Build rule for target.
Uranium: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Uranium
.PHONY : Uranium

# fast build rule for target.
Uranium/fast:
	$(MAKE) -f CMakeFiles\Uranium.dir\build.make CMakeFiles/Uranium.dir/build
.PHONY : Uranium/fast

#=============================================================================
# Target rules for targets named CuraEngine

# Build rule for target.
CuraEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 CuraEngine
.PHONY : CuraEngine

# fast build rule for target.
CuraEngine/fast:
	$(MAKE) -f CMakeFiles\CuraEngine.dir\build.make CMakeFiles/CuraEngine.dir/build
.PHONY : CuraEngine/fast

#=============================================================================
# Target rules for targets named libCharon

# Build rule for target.
libCharon: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 libCharon
.PHONY : libCharon

# fast build rule for target.
libCharon/fast:
	$(MAKE) -f CMakeFiles\libCharon.dir\build.make CMakeFiles/libCharon.dir/build
.PHONY : libCharon/fast

#=============================================================================
# Target rules for targets named cura-binary-data

# Build rule for target.
cura-binary-data: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 cura-binary-data
.PHONY : cura-binary-data

# fast build rule for target.
cura-binary-data/fast:
	$(MAKE) -f CMakeFiles\cura-binary-data.dir\build.make CMakeFiles/cura-binary-data.dir/build
.PHONY : cura-binary-data/fast

#=============================================================================
# Target rules for targets named fdm_materials

# Build rule for target.
fdm_materials: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 fdm_materials
.PHONY : fdm_materials

# fast build rule for target.
fdm_materials/fast:
	$(MAKE) -f CMakeFiles\fdm_materials.dir\build.make CMakeFiles/fdm_materials.dir/build
.PHONY : fdm_materials/fast

#=============================================================================
# Target rules for targets named signing

# Build rule for target.
signing: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 signing
.PHONY : signing

# fast build rule for target.
signing/fast:
	$(MAKE) -f CMakeFiles\signing.dir\build.make CMakeFiles/signing.dir/build
.PHONY : signing/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... projects
	@echo ... build_bundle
	@echo ... packaging
	@echo ... Cura
	@echo ... Uranium
	@echo ... CuraEngine
	@echo ... libCharon
	@echo ... package_source
	@echo ... cura-binary-data
	@echo ... package
	@echo ... fdm_materials
	@echo ... signing
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... install/local
	@echo ... install
	@echo ... install/strip
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

